### ISSUE TITLE
Sys_Error: Exceeded limit of 640 'menu' assets.

### ISSUE THREAD

**Issue by K-Faktor** [atrX/CoD4x-Server#28]
Most mods do not start due to this error Sys_Error: Exceeded limit of 640 'menu' assets.

**Comment by MichaelHillcox** [comment]
Does it happen with CoD4x too?

**Comment by K-Faktor** [comment]
Not

**Comment by K-Faktor** [comment]
This error needs to be fixed.

**Comment by atrX** [comment]
> Most mods do not start due to this error Sys_Error: Exceeded limit of 640 'menu' assets.

All mods that would work on 1.7 _should_ work just fine on Unleashed (especially seeing as all of my servers run on Unleashed and they run some fairly heavy mods). You are most likely trying to run a mod made for 1.8, which has increased asset limits. Should this somehow not be the case, could you provide me with a list of the mods you are trying to run?

As much as I would love to be able to increase the asset limits, I cannot. I will never force players to use a custom client the way the 1.8 devs have done (part of the reason this project even exists in the first place).

If any of these mods are your own, I would advise cutting down on the amount of menuDefs you have. The stock limits should honestly be fine for menuDefs (precached menus is another story though...), I've never run into them myself and I've made some fairly menu-heavy mods.

If you have questions regarding your mod you can always ask around on our forums [https://raid-gaming.net/](https://raid-gaming.net/) or on our Discord [https://discord.gg/AMHDtnD](https://discord.gg/AMHDtnD).
