### ISSUE TITLE
Add Dvar to allow clients to change their Fov

### ISSUE THREAD

**Issue by MichaelHillcox** [atrX/CoD4x-Server#4]
Add Dvar to allow clients to change their Fov
Yes please.

**Comment by atrX** [comment]
Cheat protection for cg_fovscale etc. is handled client side, unfortunately I cannot change the cheat protected flag server side. If I do ever decide to create a client patch this'll certainly be on the to-do list however.

**Comment by MichaelHillcox** [comment]
Ah. Well that sucks. Thanks anyway.
