### ISSUE TITLE
In game command to GSC notify

### ISSUE THREAD

**Issue by MichaelHillcox** [atrX/CoD4x-Server#9]
Maybe if you can. Add a way to allow in-game commands like $dosomething notify GSC script more dynamically then dvar hacking.

**Comment by atrX** [comment]
I don't use the cod4x commands myself, nor would I advise anyone to use them really. But this is easily doable by setting a dvar through say B3 and having your GSC code watch for changes in said dvar then firing a notify with the value of said dvar. Quick example for the GSC side:
```
watchB3Notify() {
	for (;;) {
		while (getDvar("b3_cmd_notify") == "") wait .05;
		level notify(getDvar("b3_cmd_notify"));
		setDvar("b3_cmd_notify", "");
	}
}
```

**Comment by atrX** [comment]
I don't advise anyone to use the cod4x commands, systems like B3 are much more modular so those are preferred. Though, with those, dvar hacking becomes your best bet. It's quite easy to do though:
```
watchB3Notify() {
	for (;;) {
		while (getDvar("b3_cmd_notify") == "") wait .05;
		level notify(getDvar("b3_cmd_notify"));
		setDvar("b3_cmd_notify", "");
	}
}
```
